### ISSUE TITLE
Kanban board Setup

### ISSUE THREAD

**Issue by AlexRS90** [AlexRS90/catalog-of-things#18]
Ruby capstone project:

Link to the kanban board: 
https://github.com/AlexRS90/catalog-of-things/projects/1

Link to the main repository:
https://github.com/AlexRS90/catalog-of-things

Team member:

 @jchernandez87 as team member 1,
 @Ntwali-Josue as team member 2
 @AlexRS90 as team member 3

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] The group tasks don't have a descriptive title.
- [ ] the above suggestion can be included in this suggestion as well, I wanted to mention it separately as well. Every point of every team member is mostly copied and pasted try to give them a descriptive title for every point. What you can do is take every bullet point in [the assignment](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) per member and make that a card.

## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AlexRS90** [comment]
Hi @mikethreels  thanks for your suggestions, I'll work on them.

**Comment by elisha2kyakpo1** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
